### PR TITLE
Ensure consistency between memory alloc and free

### LINKED ISSUE #3053: Error with cudaFreeHost(ptr) in syncedmem.hpp:30
In my case, when caffe model finishs predicting an image. There is the below error:

F0910 15:09:52.590445 21913 syncedmem.hpp:30] Check failed: error == cudaSuccess (11 vs. 0)  invalid argument
*** Check failure stack trace: ***
Aborted

It comes from CUDA_CHECK(cudaFreeHost(ptr));  in syncedmem.hpp.
Everything else works well. Any ideas for fixing this? I use latest code in the master.

I'm using Ubuntu 14.04, NVIDIA driver 352.41, Cuda 7.5 and CuDNN v2.

### PR DESCRIPTION
**Pull request by ronghanghu**
Add a bool flag to record whether a host memory is allocated using malloc or cudaMallocHost, and free correspondingly using this flag, instead of depending on Caffe::mode(), which is mutable during runtime.

This should fix #3053 .

### CODE REVIEW

**Comment by ronghanghu** [comment]
I hope to merge this PR, if no one opposes. This ensures that memories are allocated and freed consistently.

**Comment by shelhamer** [comment]
Let's hold off a bit. Although this addresses the immediate issue the root cause is that Nets do not know their own state / mode and adding more state to SyncedMem isn't necessarily how we want to work around that. However I might be convinced this is the way to go for now since it works.

**Comment by ronghanghu** [comment]
>Although this addresses the immediate issue the root cause is that Nets do not know their own state / mode and adding more state to SyncedMem isn't necessarily how we want to work around that.

I agree. In the spirit of #1500 I think it is better to have mode and device in net (or in layers if we plan to have individual mode/device for each layer).

**Comment by ronghanghu** [comment]
However, I still believe even the net knows their state/mode/device, it is still not enough, because in order to make SyncMemory and Blob self-contained data structures (not depending on the net holding it), SyncMemory class needs to know things like how memory is allocated, on which device etc.

So personally I still think a bool flag in this PR could be sort of necessary for SyncMemory. But I am open to opinions and suggestions on this issue.

File: src/caffe/syncedmem.cpp [hunk 1]
```diff
@@ -154,4 +154,3 @@ void SyncedMemory::async_gpu_push(const cudaStream_t& stream) {
 #endif
 
 }  // namespace caffe
-
```
Comment (longjon) [inline src/caffe/syncedmem.cpp]: Can we remove this whitespace change from the commit?

**Comment by shelhamer** [comment]
Alright, this is good to merge for solving the immediate issue and we will further plan #1500 for diffusing mode + device through Net, Layer, and Blob.

File: src/caffe/syncedmem.cpp (hunk 1 above)
Comment (ronghanghu) [inline src/caffe/syncedmem.cpp]: Resolved.

**Comment by ronghanghu** [comment]
This should be good now :)
